name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
stages:
- stage: create_acr
  jobs:
  - job: "create_acr"
    steps:
          - task: AzureCLI@2
            displayName: CREATE RG AND ACR
            inputs:
              azureSubscription: 'Azure subscription 1 (7c95b25d-a3ce-47f1-bee8-4fe38e644646)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                  #!/bin/bash
                  - task: AzureCLI@2
                  ACR="mydockeracrnewtoday"
                  az group create -l $LOCATION -n $RESOURCE_GROUP
                  az acr create -g $RESOURCE_GROUP -n $ACR -sku basic --admin-enable true

- stage: build_docker
  dependsOn: create_acr
  jobs:
    - job: build
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'mydockeracrnewtoday'
            repository: 'todaybuild'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/aspnet-core-dotnet-core/Dockerfile'


- stage: create_webapp_container
  dependsOn: build
  jobs:
    - job: create_app
      steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Azure subscription 1 (7c95b25d-a3ce-47f1-bee8-4fe38e644646)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            #!/bin/bash
                            az config set extension.use_dynamic_install=yes_without_prompt
                            az provider register --namespace Microsoft.App
                            RESOURCE_GROUP="RG"
                            LOCATION="eastus"
                            CONTAINERAPPS_ENVIRONMENT="tamops-environment"
                            az containerapp env create \
                                            -n $CONTAINERAPPS_ENVIRONMENT \
                                            -g $RESOURCE_GROUP \
                                            -l $LOCATION

