name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master

resources:
- repo: self


variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: create_acr
  jobs:
  - job: "create_acr"
    steps:
          - task: AzureCLI@2
            displayName: CREATE RG AND ACR
            pool:
              vmImage: $(vmImageName)
            inputs:
              azureSubscription: 'Azure subscription 1 (7c95b25d-a3ce-47f1-bee8-4fe38e644646)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                  #!/bin/bash
                  - task: AzureCLI@2
                  ACR="mydockeracrnewtoday"
                  az group create -l $LOCATION -n $RESOURCE_GROUP
                  az acr create -g $RESOURCE_GROUP -n $ACR -sku basic --admin-enable true
